# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('intro', models.TextField(default='', verbose_name='简介')),
                ('image_path', models.ImageField(blank=True, default='default_author.jpg', max_length=200, null=True, upload_to='', verbose_name='图片路径')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '小说作者',
                'verbose_name_plural': '小说作者',
                'db_table': 'tb_novel_author',
            },
        ),
    ]
