# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=32, verbose_name='小说名称')),
                ('site_name', models.CharField(max_length=32, verbose_name='小说网站')),
                ('spider_name', models.CharField(default='', max_length=64, verbose_name='爬虫名称')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='小说链接')),
                ('image_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='小说图片')),
                ('image_path', models.ImageField(blank=True, default='default_novel.jpg', max_length=200, null=True, upload_to='', verbose_name='图片路径')),
                ('intro', models.TextField(default='', verbose_name='小说简介')),
                ('read_nums', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('fav_nums', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('enable', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否已完结')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='小说作者')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'tb_novel',
            },
        ),
        migrations.CreateModel(
            name='NovelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
                'db_table': 'tb_novel_category',
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_url', models.URLField(max_length=255, unique=True, verbose_name='章节链接')),
                ('chapter_index', models.PositiveIntegerField(default=0, verbose_name='章节顺序')),
                ('chapter_name', models.CharField(max_length=255, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说章节表',
                'verbose_name_plural': '小说章节表',
                'db_table': 'tb_novel_chapter',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelCategory', verbose_name='小说分类'),
        ),
        migrations.AlterIndexTogether(
            name='novel',
            index_together=set([('novel_name', 'author')]),
        ),
    ]
